### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by AlexMBFlow** [codesbiome/electron-react-webpack-typescript-2022#28]
I cloned repository then i use yarn install, and i get this error:

Launching Application

Webpack Output Available: http://localhost:9000

⠙ Compiling Renderer Code
⠹ Compiling Renderer CodeApp threw an error during load
Error: Cannot find module '@misc/window/titlebarIPC'
    at webpackMissingModule (F:\pet\minecraft-launcher\electron-react-webpack-typescript-2022\.webpack\main\index.js:912:50)
    at Object../src/main/appWindow.ts (F:\pet\minecraft-launcher\electron-react-webpack-typescript-2022\.webpack\main\index.js:912:149)
    at __webpack_require__ (F:\pet\minecraft-launcher\electron-react-webpack-typescript-2022\.webpack\main\index.js:1065:41)
    at F:\pet\minecraft-launcher\electron-react-webpack-typescript-2022\.webpack\main\index.js:1123:68
    at F:\pet\minecraft-launcher\electron-react-webpack-typescript-2022\.webpack\main\index.js:1168:3
    at Object.<anonymous> (F:\pet\minecraft-launcher\electron-react-webpack-typescript-2022\.webpack\main\index.js:1171:12)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
⠧ Compiling Renderer Code2 assets
73 modules

ERROR in ./src/renderer/appRenderer.tsx 4:0-62
Module not found: Error: Can't resolve '@misc/window/components/WindowFrame' in 'F:\pet\minecraft-launcher\electron-react-webpack-typescript-2022\src\renderer'

webpack 5.70.0 compiled with 1 error in 9338 ms
✖ Compiling Renderer Code

Electron Forge was terminated:
ModuleNotFoundError: Module not found: Error: Can't resolve '@misc/window/components/WindowFrame' in 'F:\pet\minecraft-launcher\electron-react-webpack-typescript-2022\src\renderer'
ERROR in ./src/main/appWindow.ts 3:37-63
TS2307: Cannot find module '@misc/window/titlebarIPC' or its corresponding type declarations.
    1 | import { app, BrowserWindow } from 'electron';
    2 | import path from 'path';
  > 3 | import { registerTitlebarIpc } from '@misc/window/titlebarIPC';
      |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
    4 |
    5 | // Electron Forge automatically creates these entry points
    6 | declare const APP_WINDOW_WEBPACK_ENTRY: string;

ERROR in ./src/renderer/appRenderer.tsx 4:25-62
TS2307: Cannot find module '@misc/window/components/WindowFrame' or its corresponding type declarations.
    2 | import ReactDOM from 'react-dom';
    3 | import { inDev } from '@common/helpers';
  > 4 | import WindowFrame from '@misc/window/components/WindowFrame';
      |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    5 | import Application from './components/Application';
    6 |
    7 | // Say something

Found 2 errors in 9823 ms.
ERROR in ./src/main/appWindow.ts 3:37-63
TS2307: Cannot find module '@misc/window/titlebarIPC' or its corresponding type declarations.
    1 | import { app, BrowserWindow } from 'electron';
    2 | import path from 'path';
  > 3 | import { registerTitlebarIpc } from '@misc/window/titlebarIPC';
      |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
    4 |
    5 | // Electron Forge automatically creates these entry points
    6 | declare const APP_WINDOW_WEBPACK_ENTRY: string;

ERROR in ./src/renderer/appRenderer.tsx 4:25-62
TS2307: Cannot find module '@misc/window/components/WindowFrame' or its corresponding type declarations.
    2 | import ReactDOM from 'react-dom';
    3 | import { inDev } from '@common/helpers';
  > 4 | import WindowFrame from '@misc/window/components/WindowFrame';
      |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    5 | import Application from './components/Application';
    6 |
    7 | // Say something

Found 2 errors in 8654 ms.

**Comment by AlexMBFlow** [comment]
How to fix this?

**Comment by codesbiome** [comment]
Hello @AlexMBFlow 

Seems like you've cloned the repository using `git clone` simple command.
As per [Installation instructions](https://github.com/codesbiome/electron-react-webpack-typescript-2022#installation) you will need to clone repository with submodules to have all components for project.

```bash
# Clone repository with submodules..

git clone --recurse-submodules https://github.com/codesbiome/electron-react-webpack-typescript-2022
```

Give it a try, advise if it works fine.
Cheers!

**Comment by AlexMBFlow** [comment]
> Hello @AlexMBFlow
> 
> Seems like you've cloned the repository using `git clone` simple command. As per [Installation instructions](https://github.com/codesbiome/electron-react-webpack-typescript-2022#installation) you will need to clone repository with submodules to have all components for project.
> 
> ```shell
> # Clone repository with submodules..
> 
> git clone --recurse-submodules https://github.com/codesbiome/electron-react-webpack-typescript-2022
> ```
> 
> Give it a try, advise if it works fine. Cheers!

Ohh, Thank you! <3
