### ISSUE TITLE
Can't import ipcRenderer

### ISSUE THREAD

**Issue by codedepon** [codesbiome/electron-react-webpack-typescript-2022#38]
Not being able to import ipcRenderer in any of the components. I think it's a webpack  issue, but I'm not sure

**Comment by codesbiome** [comment]
@codedepon Can you elaborate more about the  error you getting?
If you trying to access node specific stuff in renderer process, try the config mentioned here https://github.com/codesbiome/electron-react-webpack-typescript-2022/issues/18#issuecomment-926057413

**Comment by codedepon** [comment]
That is considered unsafe, I've found a workaround, but didn't have time to propose it, if you have time, I think this should be included in the boilerplate. Here's the solution https://github.com/electron/electron/issues/9920#issuecomment-947170941
Also it's outside of this topic, but it would be nice if there was a support for css modules, and I've already opened a discussion about it and described how they would be enabled.

**Comment by codesbiome** [comment]
> That is considered unsafe, I've found a workaround, but didn't have time to propose it, if you have time, I think this should be included in the boilerplate. Here's the solution https://github.com/electron/electron/issues/9920#issuecomment-947170941

The safe approach of `contextBridge.exposeInMainWorld()` is already being used for custom window events in `misc/window` folder. 

<br>

> Also it's outside of this topic, but it would be nice if there was a support for css modules, and I've already opened a discussion about it and described how they could be enabled.

For the CSS modules approach, we will be testing the `css-loader` config you advised in discussion.
