### ISSUE TITLE
What does misc mean?

### ISSUE THREAD

**Issue by vallezw** [codesbiome/electron-react-webpack-typescript-2022#46]
Hey great project, seriously awesome and clean! But I can't figure out what misc means... Could you give a quick explanation why you called that folder that way?

**Comment by codesbiome** [comment]
Hello @vallezw, New Year Wishes 🎉

During development, that folder was containing various miscellaneous modules so we decided to keep it short named.
So this `misc` is just a short form of `Miscellaneous`

Cheers!

**Comment by vallezw** [comment]
Alright thanks and happy new year to you too!
